#ifndef APPLICATION_HARDWARE_CONFIG_H_
#define APPLICATION_HARDWARE_CONFIG_H_

#define HWCONFIG_LEDSTRIP_PRESENT
#define HWCONFIG_HTU_PRESENT
#define HWCONFIG_LIGHTSENSOR_PRESENT
#define HWCONFIG_MOTIONSENSOR_PRESENT
#define HWCONFIG_USART_PRESENT

#endif /* APPLICATION_HARDWARE_CONFIG_H_ */
